// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XcordHub.Infrastructure.Data;

#nullable disable

namespace XcordHub.Infrastructure.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260222034710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XcordHub.Entities.FederationToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ManagedInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedInstanceId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("federation_tokens", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.HubUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EmailHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SubscriptionTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("TwoFactorFailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("TwoFactorLockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("hub_users", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceBilling", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BillingExempt")
                        .HasColumnType("boolean");

                    b.Property<int>("BillingStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ManagedInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagedInstanceId")
                        .IsUnique();

                    b.ToTable("instance_billing", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureFlagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ManagedInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceLimitsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagedInstanceId")
                        .IsUnique();

                    b.ToTable("instance_configs", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceHealth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ManagedInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagedInstanceId")
                        .IsUnique();

                    b.ToTable("instance_health", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceInfrastructure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BootstrapTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CaddyRouteId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("DatabasePassword")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DockerContainerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DockerNetworkId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LiveKitApiKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("LiveKitSecretKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("ManagedInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("MinioAccessKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("MinioSecretKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RedisDb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagedInstanceId")
                        .IsUnique();

                    b.ToTable("instance_infrastructure", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.ManagedInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MemberCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OnlineCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("SnowflakeWorkerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("SnowflakeWorkerId")
                        .IsUnique();

                    b.ToTable("managed_instances", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HubUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HubUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.ProvisioningEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("ManagedInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedInstanceId");

                    b.ToTable("provisioning_events", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HubUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HubUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.WorkerIdRegistry", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.Property<DateTimeOffset>("AllocatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at");

                    b.Property<bool>("IsTombstoned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tombstoned");

                    b.Property<long?>("ManagedInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("managed_instance_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("WorkerId");

                    b.HasIndex("IsTombstoned");

                    b.HasIndex("ManagedInstanceId");

                    b.ToTable("worker_id_registry", (string)null);
                });

            modelBuilder.Entity("XcordHub.Entities.FederationToken", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithMany("FederationTokens")
                        .HasForeignKey("ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceBilling", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithOne("Billing")
                        .HasForeignKey("XcordHub.Entities.InstanceBilling", "ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceConfig", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithOne("Config")
                        .HasForeignKey("XcordHub.Entities.InstanceConfig", "ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceHealth", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithOne("Health")
                        .HasForeignKey("XcordHub.Entities.InstanceHealth", "ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.InstanceInfrastructure", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithOne("Infrastructure")
                        .HasForeignKey("XcordHub.Entities.InstanceInfrastructure", "ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.ManagedInstance", b =>
                {
                    b.HasOne("XcordHub.Entities.HubUser", "Owner")
                        .WithMany("ManagedInstances")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("XcordHub.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("XcordHub.Entities.HubUser", "HubUser")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("HubUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HubUser");
                });

            modelBuilder.Entity("XcordHub.Entities.ProvisioningEvent", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithMany("ProvisioningEvents")
                        .HasForeignKey("ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.RefreshToken", b =>
                {
                    b.HasOne("XcordHub.Entities.HubUser", "HubUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("HubUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HubUser");
                });

            modelBuilder.Entity("XcordHub.Entities.WorkerIdRegistry", b =>
                {
                    b.HasOne("XcordHub.Entities.ManagedInstance", "ManagedInstance")
                        .WithMany()
                        .HasForeignKey("ManagedInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedInstance");
                });

            modelBuilder.Entity("XcordHub.Entities.HubUser", b =>
                {
                    b.Navigation("ManagedInstances");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("XcordHub.Entities.ManagedInstance", b =>
                {
                    b.Navigation("Billing");

                    b.Navigation("Config");

                    b.Navigation("FederationTokens");

                    b.Navigation("Health");

                    b.Navigation("Infrastructure");

                    b.Navigation("ProvisioningEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
